# -*- coding: utf-8 -*-
# Transcribed from "10x14 Phnom Penh Menu Editable", supplied by the owner.
# (name, chinese, vietnamese, price, description, tags)
MENU = [
 ("Share Plates", None, [
  ("Phnom Penh Chicken Wings (S/L)","金邊酥炸雞翼","Cánh Gà Chiên","17/23","Crispy wings tossed with garlic, scallion and butter, served with Phnom Penh's signature lemon pepper sauce",["GF"]),
  ("Phnom Penh Garlic Squid (S/L)","金邊椒鹽吊片","Mực Rang Muối","18/26","Crispy squid with garlic, scallion and butter, and lemon pepper sauce",["GF"]),
  ("Phnom Penh Garlic Prawns (S/L)","金邊椒鹽蝦","Tôm Rang Muối","18/26","Crispy shell-on prawns fried with garlic, scallion and butter, served with lemon pepper sauce",["GF"]),
  ("Phnom Penh Garlic Spareribs (S/L)","金邊椒鹽排骨","Sườn Non Rang Muối","17/23","Crispy pork, garlic, scallion and butter served with lemon pepper sauce",[]),
  ("Butter Beef","牛油生牛肉","Bò Tái Bơ","24.95","Thinly sliced rare beef topped with homemade garlic chips, cilantro and Phnom Penh special sauce",[]),
  ("Spring Rolls (4pc/7pc)","越式炸春卷","Chả Giò","10/17.5","Crispy rolls filled with minced pork, prawn, taro, carrot and vermicelli, served with fish sauce",[]),
  ("Crab Rolls","潮州蟹棗","Chả Giò Triều Châu","24.95","Minced pork, prawn and crab with jicama, wrapped in bean curd, served with chili hoisin sauce",[]),
  ("Salad Roll","越式沙律卷","Gỏi Cuốn","7","Choice of prawn and pork, beef, or shredded pork skin. Served with peanut sauce or fish sauce",[]),
  ("Beef Skewers (2pc/4pc)","串燒牛柳","Bò Nướng","17/34","Grilled lemongrass beef skewers with red pepper, onion and vermicelli, served with fish sauce",[]),
  ("Sugarcane Prawns (2pc/4pc)","越式蔗蝦","Chảo Tôm","17/34","Prawn paste wrapped on sugarcane, fried until golden, served with vermicelli and fish sauce",[]),
  ("Fried Fish Cake","香茅炸魚餅","Chả Cá Chiên","26","Fish and squid paste with lemongrass, served with pickled vegetables",[]),
  ("Fried Prawn Balls","炸蝦丸","Tôm Viên Chiên","21","Homemade prawn balls served with chili hoisin sauce",[]),
  ("Golden Fish (Pomfret)","煎倉魚","Cá Chìm Chiên Giòn","27","Whole golden pomfret fried to crisp perfection",[]),
  ("Salt &amp; Pepper Crab","金邊椒鹽蟹","Cua Rang Muối","mp","Deep-fried crab with garlic and salt-pepper seasoning. Order in advance",[]),
  ("Tamarind Crab","金邊酸子蟹","Cua Rang Me","mp","Deep-fried crab tossed in spicy tamarind sauce. Order in advance",[]),
  ("Green Papaya Salad","木瓜絲沙律","Gỏi Đu Đủ","27","Papaya slaw with prawns, beef jerky, peanuts and special vinaigrette",[]),
  ("Trieu Chau Chive Dumplings","潮州韭菜包","Bánh Hẹ Triều Châu","16","Homemade dumplings stuffed with Chinese chives, pan-fried, served with fish sauce",["GF","V"]),
  ("Spicy Basil Clams","香草炒蜆","Nghêu Xào Rau Quế","25","Clams stir-fried with garlic, chili and Thai basil",["GF"]),
  ("Black Pepper Squid","黑椒魷魚","Mực Rang Tiêu","26","Stir-fried squid with black pepper sauce and caramelized onion",["GF"]),
  ("Oyster Pancake","潮州煎蠔烙","Hào Chiên Triều Châu","24.95","Crispy egg batter with oysters, served with spicy fish sauce",["GF"]),
  ("Vietnamese Crispy Crepe","越式煎餅","Bánh Xèo","24.5","Coconut-infused crepe with pork, shrimp, bean sprouts and mung bean, served with fish sauce",[]),
 ]),
 ("Cambodian Style Noodles","Served with beansprouts, lime and cilantro. Choice of rice, egg or mixed noodles, add $2.", [
  ("Noodle Soup – Nuoc","金邊湯粿條","Hủ Tiếu Nam Vang","16","Light broth with prawns, pork, liver and heart",["GF"]),
  ("Dry Noodles – Kho","金邊乾撈粿條","Hủ Tiếu Nam Vang Khô","16","Garlic oil and soy-sauce tossed noodles with prawns, pork, liver and heart, served with pork bone soup",[]),
  ("Stew Beef Noodle Soup – Bò Kho","牛腩粉","Hủ Tiếu Bò Kho","17.5","Rich tomato broth with tender beef brisket, tendon and carrots",["GF"]),
  ("Meatball Noodle Soup – Nuoc","丸子湯粉","Hủ Tiếu Thịt Viên","18.5","Light pork broth. Choice of beef, squid, fish, prawn or assorted",[]),
  ("Dry Noodles with Meatballs – Kho","乾撈丸子粉","Hủ Tiếu Khô Thịt Viên","18.5","Garlic oil and soy-sauce tossed noodles, served with pork bone soup. Choice of beef, squid, fish, prawn or assorted",[]),
  ("Phnom Penh Phở","牛肉河粉","Phở Nam Vang","17.5","Aromatic beef broth with rare beef, brisket, beef balls and tendon, served with rice noodles",["GF"]),
 ]),
 ("Rice Dishes", None, [
  ("Lemongrass Pork Chop Rice","香茅豬扒飯","Cơm Sườn","16.5","Tender grilled lemongrass pork chop with scallion oil, jasmine rice and pork bone soup",[]),
  ("Lemongrass Chicken Rice","香茅燒雞飯","Cơm Gà Nướng Xả","16.5","Juicy grilled lemongrass chicken with scallion oil, jasmine rice and pork bone soup",[]),
  ("Beef Luc Lac Rice","牛肉飯","Cơm Bò Lúc Lắc","19.5","Wok-seared beef, jasmine rice and pork bone soup",[]),
  ("Phnom Penh Jumbo Rice","八寶飯","Cơm Đặc Biệt","22","Choice of chicken or pork, with scallion oil, Vietnamese ham, shredded pork and skin, and egg",[]),
  ("Trieu Chau Fried Rice","潮州炒飯","Cơm Chiên Triều Châu","20","Chinese sausage, egg, scallion and carrots",[]),
  ("Shrimp Fried Rice","蝦仁炒飯","Cơm Chiên Tôm","22","Shrimp, egg, scallion and carrots",[]),
  ("Vegetable Fried Rice","素菜炒飯","Cơm Chiên Chay","20","Vegetables, egg, scallion and carrots",["V"]),
 ]),
 ("Vietnamese Entrées", None, [
  ("Filet Beef Luc Lac","牛肉","Bò Lúc Lắc","29","Tender stir-fried beef with fresh greens",[]),
  ("Lemongrass Pork","香茅燒豬扒","Sườn Nướng Xả","18","Grilled lemongrass pork chop with scallion oil",[]),
  ("Lemongrass Chicken","香茅燒雞腿","Gà Nướng Xả","18","Grilled lemongrass chicken with scallion oil",[]),
  ("Fried Rice Cake","潮州煎糕","Bọt Chiên","18","Crispy fried rice cakes with scallion, egg, beansprout and preserved radish, served with spicy soy dip",["V"]),
  ("Steamed Rice Rolls","越式蒸粉卷","Bánh Cuốn","18","Rice rolls filled with minced pork and mushroom, with Vietnamese ham and beansprout",["GF"]),
  ("Steamed Rice Cake","越式蒸餅仔","Bánh Bèo","18","Steamed rice cakes with minced pork, prawn and coconut milk",["GF"]),
  ("Beef Vermicelli Bowl","越式牛肉米粉","Bún Bò Xào","18","Beef with onion, red pepper, beansprout, cucumber and vermicelli, topped with peanuts",[]),
  ("Spring Roll Vermicelli Bowl","越式炸春卷米粉","Bún Chả Giò","18","Crispy spring rolls with beansprout, cucumber and vermicelli, topped with peanuts",[]),
  ("Special Combo A","套盤 A","Phần Ăn A","25","Spring roll, beef skewer and sugarcane prawn with vermicelli and fish sauce",[]),
  ("Special Combo B","套盤 B","Phần Ăn B","25","Spring roll, steamed rice roll and sugarcane prawn with vermicelli and fish sauce",[]),
  ("Special Combo C","套盤 C","Phần Ăn C","25","Steamed rice roll, beef skewer and sugarcane prawn with vermicelli and fish sauce",[]),
 ]),
 ("Soup &amp; Claypot", None, [
  ("Seaweed Meatball Soup (S/L)","紫菜雙丸湯","Súp Rong Biển","21/42","",[]),
  ("Hot &amp; Sour Soup (S/L)","金邊酸湯","Canh Chua","22/44","Simmered with tomato, pineapple and taro stem. Choice of fish, chicken or prawn",["GF"]),
  ("Stew Beef Claypot","牛腩煲","Bò Kho Nam Vang","24","Tomato broth with beef flank, tendon and carrots, served with jasmine rice",["GF"]),
  ("Curry Chicken Claypot","金邊咖哩雞煲","Cà Ri Gà Nam Vang","24","Braised chicken with onion, sweet potato and coconut milk, served with jasmine rice",[]),
  ("Braised Pork Claypot","紅燒沙煲豬肉蛋","Thịt Kho","24","Braised pork belly with egg in rich Vietnamese sauce, served with jasmine rice",[]),
  ("Cha Kapeek","椰香肉醬","Kappip","22","Fermented shrimp paste mixed with pork, with a side of cabbage",[]),
 ]),
 ("Vegetable Dishes", None, [
  ("Baby Lotus Stem","炒蓮藕苗","Ngó Sen Xào","27","Stir-fried lotus stem with garlic, scallion and fish sauce",["GF"]),
  ("Morning Glory","炒通菜","Rau Muống Xào","24","Stir-fried morning glory with chili and fermented soy bean",["GF"]),
  ("Beef with Beansprouts","銀芽炒牛肉","Ngò Gai Xào Thịt Bò","28","Stir-fried beef with beansprout and lemongrass, served with fish sauce",[]),
  ("Pea Tips","清炒豆苗","Ngọn Đậu Xào","26","Tender pea tips stir-fried with garlic in a light broth",["GF"]),
  ("Gai Lan","清炒芥蘭","Cải Làn Xào","22","Stir-fried Chinese broccoli with garlic and ginger",["GF"]),
 ]),
 ("Desserts", None, [
  ("Durian Sticky Rice","榴槤糯米飯","Xôi Sím","11","Sticky rice with durian and coconut milk",[]),
  ("Nine Layer Cake","九層糕","Bánh Da Lợn","11","Steamed dessert made of pandan and mung bean layers",[]),
  ("Lotus Seed Tapioca","蓮子西米露","Chè Sen","11","Lotus seeds and tapioca pearls in coconut cream",[]),
  ("Black Glutinous Rice","黑糯米飯","Nếp Than","9","Sweet black sticky rice topped with coconut milk",[]),
  ("Taro Tapioca","芋頭西米露","Chè Khoai Môn","9","Warm taro with sago in sweet coconut soup",[]),
  ("Caramel Custard","焦糖布丁","Bánh Flan","9","Silky caramel custard with a light sweetness",[]),
  ("Coconut Jello","椰子果凍","Dừa Rau Câu","9","Refreshing coconut jelly",[]),
  ("Three Colour Dessert","三色冰","Chè Ba Màu","9","Classic Vietnamese layered dessert with beans, jelly and sweetened condensed milk",[]),
 ]),
 ("Drinks", "Alcohol prices include applicable taxes.", [
  ("Vietnamese Iced Coffee","越南凍奶咖啡","Cà Phê Sữa Đá","7","Strong drip coffee mixed with sweetened condensed milk",[]),
  ("Lime Soda","青檸梳打","Soda Chanh","7","Refreshing soda with fresh lime",[]),
  ("Salted Plum Soda","鹹酸梅梳打","Nước Chanh Muối","7","Soda with preserved salted plum",[]),
  ("Egg Soda","雞蛋奶梳打","Soda Sữa Hột Gà","7","Soda with egg yolk and condensed milk",[]),
  ("Lime Iced Tea","凍檸茶","Trà Chanh","8","Vietnamese-style iced tea with lime",[]),
  ("Fresh Squeezed Orange Juice","鮮榨橙汁","Cam Vắt","8","Freshly pressed orange juice",[]),
  ("Soy Milk","豆漿","Sữa Đậu Nành","4","Hot or cold",[]),
  ("Fruit Smoothie","生果冰沙","Sinh Tố","9.5","Choice of lychee, strawberry or jackfruit",[]),
  ("Seasonal Fruit Smoothie","生果冰沙","Sinh Tố","11","Choice of durian or mango",[]),
  ("Ice Crush","碎冰","Nước Đá","8","Choice of lychee, green bean, lotus seed, lime jelly or black jelly",[]),
  ("Soft Drinks","汽水","Nước Ngọt","3","Coke, Coke Zero, Sprite, Ginger Ale",[]),
  ("_subsection_Seltzers",None,None,None,None,[]),
  ("Lychee Fizz",None,None,"5","A sweet, floral lychee-flavoured seltzer with crisp bubbles that gives a refreshing tropical feel. 355ml",[]),
  ("Green Grape",None,None,"5","A light, bubbly seltzer with juicy green grape flavour that balances crispness and gentle sweetness. 355ml",[]),
  ("HK Lemon",None,None,"5","A bold and refreshing blend of citrusy lemon and black tea inspired by classic Hong Kong street-style lemon tea. 355ml",[]),
  ("_subsection_Wine",None,None,None,None,[]),
  ("Jackson-Triggs Merlot (House Red)",None,None,"7/17","6oz or ½ litre",[]),
  ("Jackson-Triggs Pinot Grigio (House White)",None,None,"7/17","6oz or ½ litre",[]),
  ("Cabernet Sauvignon – Liberty School",None,None,"58","",[]),
  ("Cabernet Sauvignon – Casillero del Diablo",None,None,"37","",[]),
  ("Merlot – Beringer Founders Estate",None,None,"50","",[]),
  ("Sauvignon Blanc – Whitehaven",None,None,"58","",[]),
  ("Pinot Gris – Kim Crawford",None,None,"54","",[]),
  ("Sauvignon Blanc – White Hills",None,None,"52","",[]),
  ("_subsection_Beer",None,None,None,None,[]),
  ("Tsingtao",None,None,"8","330ml",[]),
  ("Sapporo",None,None,"8","330ml",[]),
  ("Heineken",None,None,"8","330ml",[]),
 ]),

]
ADDONS = [("Egg","蛋","Trứng","2"),("Shredded Pork","肉絲","Bi","2.5"),
          ("Vietnamese Ham","扎肉","Chả Lụa","2.5"),("Fried Rice","炒飯","Cơm Chiên","5")]

# Choices are bold and structural on the printed menu, not part of the description.
CHOICES = {
 "Golden Fish (Pomfret)":            "Garlic Soy | Fish Sauce",
 "Salad Roll":                       "Prawn &amp; Pork | Beef | Shredded Pork Skin",
 "Meatball Noodle Soup – Nuoc":       "Beef | Squid | Fish | Prawn | Assorted",
 "Dry Noodles with Meatballs – Kho":  "Beef | Squid | Fish | Prawn | Assorted",
 "Phnom Penh Jumbo Rice":            "Chicken | Pork",
 "Seaweed Meatball Soup (S/L)":      "Beef | Squid | Fish | Prawn | Assorted",
 "Hot &amp; Sour Soup (S/L)":        "Fish | Chicken | Prawn",
 "Fruit Smoothie":                   "Lychee | Strawberry | Jackfruit",
 "Seasonal Fruit Smoothie":          "Durian | Mango",
 "Ice Crush":                        "Lychee | Green Bean | Lotus Seed | Lime Jelly | Black Jelly",
}
# descriptions with the choice text folded in, rewritten without it
DESC_FIX = {
 "Golden Fish (Pomfret)":            "Whole golden pomfret fried to crisp perfection",
 "Salad Roll":                       "Served with peanut sauce or fish sauce",
 "Meatball Noodle Soup – Nuoc":       "Light pork broth",
 "Dry Noodles with Meatballs – Kho":  "Garlic oil and soy-sauce tossed noodles, served with pork bone soup",
 "Phnom Penh Jumbo Rice":            "With scallion oil, Vietnamese ham, shredded pork and skin, and egg",
 "Seaweed Meatball Soup (S/L)":      "",
 "Hot &amp; Sour Soup (S/L)":        "Simmered with tomato, pineapple and taro stem",
 "Fruit Smoothie":                   "",
 "Seasonal Fruit Smoothie":          "",
 "Ice Crush":                        "",
 "Soy Milk":                         "Hot | Cold",
 "Soft Drinks":                      "Coke, Coke Zero, Sprite, Ginger Ale",
}
# the two line note printed under the section heading
EXTRA_LINE = {"Gai Lan": "Add beef +6"}
NOTES = {
 "Cambodian Style Noodles": ("Choice of Rice, Egg, or Mixed Noodles +$2", "Beansprouts, lime, cilantro"),
}
